### PR TITLE
Feature/hexxle 88 - AudioManager

### PR DESCRIPTION
**Pull request by denadex**
Implemented Brackey's AudioManager but not too happy with it...
Sounds need to be added via Unity and are in an array which the order cannot be changed.(items can only be added/deleted) But should still do it for our project

Added a PlayRandomPop() method to add variety.

Added two unit tests which check if the main theme is running in both scenes.
And one that checks if the AudioManager plays the correct sound.

Renamed the scenes folders and the scenes themselves.

Added AudioManager as a prefab.

Based with the latest development commit

### CODE REVIEW

**Comment by denadex** [comment]
1 Test failed ...

**Comment by denadex** [comment]
Would be nice if somone else could try this branch out on his or her PC...
Andrews instance passes all checks but he can't hear any sound(?)

Having trouble to find out what the problem might be....

**Comment by DennisBannerman** [comment]
Passes all checks for me, sound works too! Great work, excellent choice of sounds and music! Haven't gone through the code yet though.

**Review by DennisBannerman — APPROVED** [review]
Looks good. Two things I'd like to note however:

- How about turning the sound names into an enum? The way it's currently setup, if we end up changing one of the sound names or whatever, we'd have to go full ctrl+f through the code to find all string instances of "pause" for example.
- I'm not that fond of the foreach loops. I realize Unity puts them in an array, but wouldn't a separate dictionary with name+index make it possible to access the array by index instead of foreach'ing everytime?

**Review by RicardoMonteiroSimoes — CHANGES_REQUESTED** [review]
Implementation seems to work on my machine and plays sounds - albeit I think the "Pause Menu" sound is very unreliable, as it doesnt seem to always trigger. Suggestions:

Instead of using on array, why not use generic lists? Something like this

```csharp
        public List<Sound> popSounds = new List<Sound>();
        public List<Sound> backgroundSounds = new List<Sound>();
        public List<Sound> pauseSounds = new List<Sound>();
```

this would allow the grouping of sounds that are for the same goal, and then one can simply use a random function to play one of them.

Also I'd suggest trying to change the code to not rely on any "names" files might have, but solely on the list theyre inside. I.e., for testing you could then do:


```csharp
Assert.True(audioManager.backgroundSounds.Any(s => s.isPlaying));
```

**Comment by RicardoMonteiroSimoes** [comment]
Okay, I tried it again:
The pause sound doesnt seem to trigger when pressing `Esc`. 

I'm also trying to fix the failing test on a different branch, I suspect it has something to do with the cloud based testrunner.

**Comment by N2Drew** [comment]
> Would be nice if somone else could try this branch out on his or her PC...
> Andrews instance passes all checks but he can't hear any sound(?)
> 
> Having trouble to find out what the problem might be....

My bad, just noticed that I had "Mute Audio" enabled in the editor.

**Comment by RicardoMonteiroSimoes** [comment]
> Okay, I tried it again:
> The pause sound doesnt seem to trigger when pressing `Esc`.
> 
> I'm also trying to fix the failing test on a different branch, I suspect it has something to do with the cloud based testrunner.

I managed to fix this in #21

**Review by N2Drew — APPROVED** [review]
Is sufficient for now. Maybe down the line make it more flexible, given there's enough time.
Love the sounds :)

**Review by deSaoJose — APPROVED** [review]

**Comment by denadex** [comment]
@RicardoMonteiroSimoes  @DennisBannerman  Could you guys have another look to verify if it fullfills your expectations :)

**Comment by RicardoMonteiroSimoes** [comment]
> @RicardoMonteiroSimoes @DennisBannerman Could you guys have another look to verify if it fullfills your expectations :)

Looks good to me! Not sure about these testbits:

```csharp
            foreach (Sound sound in audioManager.backgroundSounds)
            {
                if (sound.source.isPlaying)
                {
                    audioSource = sound.source;
                }
            }
```

but we can refactor that at a later stage

**Review by RicardoMonteiroSimoes — APPROVED** [review]

**Comment by denadex** [comment]
> 
> 
> > @RicardoMonteiroSimoes @DennisBannerman Could you guys have another look to verify if it fullfills your expectations :)
> 
> Looks good to me! Not sure about these testbits:
> 
> ```cs
>             foreach (Sound sound in audioManager.backgroundSounds)
>             {
>                 if (sound.source.isPlaying)
>                 {
>                     audioSource = sound.source;
>                 }
>             }
> ```
> 
> but we can refactor that at a later stage

what would you suggest?
something like this?
```cs
            int counter = 0;
            foreach (Sound sound in audioManager.backgroundSounds)
            {
                if (sound.source.isPlaying)
                {
                    counter++;
                }
            }

            yield return new WaitForSecondsRealtime(1);

            Assert.True(counter == 1);
```
there should only be 1 background"sound/music" playing at once

**Pull request merged**
