### PR TITLE
feature/HEXXLE-185: Implemented previously defined colour scheme

### PR DESCRIPTION
**Pull request by N2Drew**
Changes:
- Materials for blue, red, yellow, green, purple tiles
- 2D sprites for blue red, yellow, green, purple tiles
- Updated blue of the title screen
- Updated blue of the score progress bar

Note: The materials' colours appear a bit washed out, not as vibrant as the sprites. It may be possible to improve the look of the materials, but for the time being, it works as it is.

### CODE REVIEW

**Review by RicardoMonteiroSimoes — APPROVED** [review]
It looks too good with the new skybox, god damn 🔥🔥🔥

**Review by denadex — APPROVED** [review]
Only one thing left to say - Perle

**Review by DennisBannerman — APPROVED** [review]
SeemsGood

Just realized, we still need to get rid of the writing on the stack tiles.

**Comment by RicardoMonteiroSimoes** [comment]
> SeemsGood
> 
> Just realized, we still need to get rid of the writing on the stack tiles.

I'd say that the writing can stay for the MVP, as we might decide to showcase anything

**Pull request merged**
