### PR TITLE
HEXXLE-72 and HEXXLE-73: Camera Controls

### PR DESCRIPTION
**Pull request by N2Drew**
Implemented the basic features necessary for simple camera controls: This includes:

- Camera movement using WASD and arrow keys
- Camera zoom using the mouse scroll wheels
- In theory, support for many more input devices (hip and cool Unity Input System)
- Select few public variables for configuring things like camera speed
- Six units tests (PlayMode) that all run successfully

### CODE REVIEW

**Review by DennisBannerman — APPROVED** [review]
Nice work! Looks good to me. One single thing with the enable/disable for events though; I found we haven't been using it quite right. If you "rejoin" the game multiple times, the game will end up executing every event multiple times.

I'll explain it in the next meeting. Otherwise have a look at [this](https://github.com/hexxler/hexxle_game/pull/16#issuecomment-817210796) for commit 86b3f84ef7796c35824582c7b9a530909b031845

**Review by denadex — APPROVED** [review]
Nice!

**Review by RicardoMonteiroSimoes — APPROVED** [review]
Good feature, good implementation. I've noticed a bug I'm going to add to jira tho:
the map system starts to fail on far away spots - i.e., when moving down right, the rendering stops on a virtual border, and up top it wont let me add more tiles, but starts stacking them on top of each other. I assume this has nothing to do with the camera system tho.

**Comment by N2Drew** [comment]
Regarding the bug(s): See the comment at HEXXLE-93 (the thing Ricardo covered), I found a few interesting things that may or may not help us .

**Review by deSaoJose — APPROVED** [review]

**Pull request merged**
