### PR TITLE
Feature/hexxle 74 stack to UI

### PR DESCRIPTION
**Pull request by deSaoJose**

### CODE REVIEW

**Review by DennisBannerman — APPROVED** [review]
Looks good to me!

**Review by denadex — APPROVED** [review]
Good job!

**Review by RicardoMonteiroSimoes — COMMENTED** [review]
Code wise it looks good to me - I have a question regarding the new tiles. Those have been changed from using the 3D model to use a simple 2d texture. Whilst this seems to work, it looks like a lot of additional time would be needed to add new tiles. Is there no other way to directly use the material of the tiles? As in, instead of creating a new material + a new texture, we could just reuse the material for the ui elements?

**Review by N2Drew — APPROVED** [review]
Looks good to me :)

**Pull request merged**
